esphome:
  name: dalila-relay
  friendly_name: Dalila_Relay

  on_boot:
    priority: 600
    then:
      - script.execute: blink_relay1
      - script.execute: blink_relay2
      - script.execute: blink_relay3
      - script.execute: blink_relay4


esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dalila-Relay-Config"
    password: ""

captive_portal:

web_server:
  port: 80
  auth:
    username: "admin"
    password: "password"


status_led:
  pin: GPIO02


# Configuração dos relés físicos
switch:
  - platform: gpio
    name: "Cabaça 1"
    icon: "mdi:fan"
    pin: GPIO25
    id: relay1_switch
    restore_mode: ALWAYS_OFF


  - platform: gpio
    name: "Cabaça 2"
    icon: "mdi:fan"
    pin: GPIO26
    id: relay2_switch
    restore_mode: ALWAYS_OFF


  - platform: gpio
    name: "Cabaça 3"
    icon: "mdi:fan"
    pin: GPIO33
    id: relay3_switch
    restore_mode: ALWAYS_OFF


  - platform: gpio
    name: "Cabaça 4"
    icon: "mdi:fan"
    pin: GPIO32
    id: relay4_switch
    restore_mode: ALWAYS_OFF

button:
  - platform: template
    name: "Reinicia Sequência"
    on_press:
      - logger.log: "Reiniciando sequência dos relês."
      - script.stop: blink_relay1
      - script.stop: blink_relay2
      - script.stop: blink_relay3
      - script.stop: blink_relay4
      
      - switch.turn_off: relay1_switch
      - switch.turn_off: relay2_switch
      - switch.turn_off: relay3_switch
      - switch.turn_off: relay4_switch

      - delay: "1s"
      - script.execute: blink_relay1
      - script.execute: blink_relay2
      - script.execute: blink_relay3
      - script.execute: blink_relay4


# Script para modo síncrono (executa relês em sequência)

script:

# Modo Assíncrono
  - id: blink_relay1
    mode: parallel
    then:
      - while:
          condition: 
            lambda: 'return true;'
          then:
          - logger.log: "Inicio Cabaça 1"
          - switch.turn_on: relay1_switch
          - delay: "3s"
          - switch.turn_off: relay1_switch
          - delay: "15s"
          - switch.turn_on: relay1_switch
          - delay: "4s"
          - switch.turn_off: relay1_switch
          - delay: "15s"
          - switch.turn_on: relay1_switch
          - delay: "4s"
          - switch.turn_off: relay1_switch
          - delay: "19s"

  - id: blink_relay2
    mode: parallel
    then:
      - while:
          condition:
            lambda: 'return true;'
          then:
            - logger.log: "Inicio Cabaça 2"
            - switch.turn_off: relay2_switch
            - delay: "3s"
            - switch.turn_on: relay2_switch
            - delay: "3s"
            - switch.turn_off: relay2_switch
            - delay: "20s"
            - switch.turn_on: relay2_switch
            - delay: "5s"
            - switch.turn_off: relay2_switch
            - delay: "25s"
            - switch.turn_on: relay2_switch
            - delay: "4s"

  - id: blink_relay3
    mode: parallel
    then:
      - while:
          condition:
            lambda: 'return true;'
          then:
            - logger.log: "Inicio Cabaça 3"
            - switch.turn_off: relay3_switch
            - delay: "6s"
            - switch.turn_on: relay3_switch
            - delay: "4s"
            - switch.turn_off: relay3_switch
            - delay: "23s"
            - switch.turn_on: relay3_switch
            - delay: "5s"
            - switch.turn_off: relay3_switch
            - delay: "18s"
            - switch.turn_on: relay3_switch
            - delay: "4s"

  - id: blink_relay4
    mode: parallel
    then:
      - while:
          condition:
            lambda: 'return true;'
          then:
            - logger.log: "Inicio Cabaça 4"
            - switch.turn_off: relay4_switch
            - delay: "10s"
            - switch.turn_on: relay4_switch
            - delay: "5s"
            - switch.turn_off: relay4_switch
            - delay: "18s"
            - switch.turn_on: relay4_switch
            - delay: "4s"
            - switch.turn_off: relay4_switch
            - delay: "18s"
            - switch.turn_on: relay4_switch
            - delay: "5s"
